import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import FooterStrip from "@/components/FooterStrip";
import { connectDB } from "@/database/db";
import { Toaster } from "@/components/ui/sonner";
import SessionWrapper from "@/SessionWrapper";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],

  variable: "--font-poppins",
});

export const metadata = {
  title: "Quick Cart - Home",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default async function RootLayout({ children }) {
    await connectDB()

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <SessionWrapper>
          <Navbar />
          {children}
          <Footer />
          <FooterStrip />
          <Toaster position="top-center" richColors />
        </SessionWrapper>
      </body>
    </html>
  );
}
